### PR TITLE
fix: handle all subtypes of HeadersInit

### LINKED ISSUE #25: usage of spread operator with HeadersInit leads to unexpected behavior or errors
Here's an example from `json`:

https://github.com/satyarohith/sift/blob/424d5b736f7ed11ac33463a11928085767859dd9/mod.ts#L227-L252

On line 249, if `init.headers` is of type `HeadersInit` (which is `Headers | string[][] | Record<string, string>`). However, if it is not `Record<string, string>`, this usage of the spread operator will lead to unexpected behavior or errors.

### PR DESCRIPTION
**Pull request by jsejcksn**
resolves #25

Hi @satyarohith. PTAL. A new test is probably needed, but I'm not sure how you are testing this module, so I'm not sure how to contribute in that area. (`deno test --unstable --prompt` throws all sorts of compiler type errors for me.)

### CODE REVIEW

**Comment by jsejcksn** [comment]
Re: tests

I peeked at the [CI workflow file](https://github.com/satyarohith/sift/blob/424d5b736f7ed11ac33463a11928085767859dd9/.github/workflows/ci.yml) and saw that you are skipping type checking for the tests right now, so I added some tests (and updated the module and test dependencies).

File: test.ts [hunk 1]
```diff
@@ -190,3 +190,66 @@ Deno.test("validateRequest() populates body as per schema", async () => {
...
+    },
+    entries: [
+      ["content-type", "type/subtype"],
+      ["custom-header-1", "1"],
+      ["custom-header-2", "2"],
+    ],
+  },
+];
+
+for (const { entries, headers, description } of headersInitCases) {
```
Comment (satyarohith) [inline test.ts:240]: Nice :)

**Review by satyarohith — APPROVED** [review]
Thanks for the contribution, @jsejcksn! :)

I think you need to run `deno fmt` to fix the CI.

LGTM otherwise.

File: test.ts (hunk 1 above)
Comment (jsejcksn) [reply test.ts:240]: @satyarohith This can be extended for [`newResponse`](https://github.com/satyarohith/sift/blob/89a293c7f93fb9fda0bee4c9d147f376b0006bac/mod.ts#L60-L85) if you want to export it for testing. However, I didn't do that for a couple of reasons:

1. I didn't want to modify the API of the existing exports.
2. From looking at the code and comments, it seems like that function is only meant to be used internally to fulfill a temporary issue with deno deploy.
